name: SimpleAPI(CD)

on: [deployment]

jobs:

  deployment:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy
      uses: deliverybot/helm@master
      with:
        token: ${{ github.token }}
        secrets: ${{ toJSON(secrets) }}
        version: ${{ github.sha }}
        chart: app
      env:
        KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}